services:
  - type: web
    name: language-translator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
    region: oregon
    branch: main
